name: Build and Package App with PyInstaller

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      
      - name: Build with PyInstaller
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            pyinstaller App_PP.py --noconsole --onefile --distpath build/windows --name Kaalen-v1.0 --icon icon.ico
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            pyinstaller App_PP.py --windowed --onefile --distpath build/macos --name Kaalen-v1.0 --icon icon.ico
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pyinstaller App_PP.py --onefile --distpath build/linux --name Kaalen-v1.0
          fi
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kaalen-${{ matrix.os }}
          path: build/*
          retention-days: 7

  create-release:
    needs: build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip Windows artifact
        run: |
          cd artifacts/Kaalen-windows-latest
          zip -r ../../Kaalen-windows.zip .

      - name: Zip macOS artifact
        run: |
          cd artifacts/Kaalen-macos-latest
          zip -r ../../Kaalen-macos.zip .

      - name: Zip Linux artifact
        run: |
          cd artifacts/Kaalen-ubuntu-latest
          zip -r ../../Kaalen-linux.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Kaalen-windows.zip
            Kaalen-macos.zip
            Kaalen-linux.zip
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}-${{ github.run_number }}
          body: |
            This is an automated release.
            
            This release includes standalone executables for Windows, macOS, and Linux.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
