name: Build and Package App with PyInstaller

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      
      - name: Build with PyInstaller
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            pyinstaller App_PP.py --noconsole --onefile --distpath build/Kaalen-windows --name Kaalen-v.1.0 --icon icon.ico
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            pyinstaller App_PP.py --windowed --onefile --distpath build/Kaalen-macos --name Kaalen-v.1.0 --icon icon.ico
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pyinstaller App_PP.py --onefile --distpath build/Kaalen-linux --name Kaalen-v.1.0
          fi
        shell: bash

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kaalen-App-${{ matrix.os }}
          path: build/Kaalen-${{ matrix.os }}
          retention-days: 7

  create-release:
    needs: build-binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip Windows artifact
        run: |
          cd artifacts/Kaalen-App-windows-latest/Kaalen-windows
          zip -r ../../../../Kaalen-windows.zip .
      - name: Zip macOS artifact
        run: |
          cd artifacts/Kaalen-App-macos-latest/Kaalen-macos
          zip -r ../../../../Kaalen-macos.zip .

      - name: Zip Linux artifact
        run: |
          cd artifacts/Kaalen-App-ubuntu-latest/Kaalen-linux
          zip -r ../../../../Kaalen-linux.zip .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Kaalen-windows.zip
            Kaalen-macos.zip
            Kaalen-linux.zip
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}-${{ github.run_number }}
          body: |
            This is an automated release.
            
            This release includes a standalone executables for Windows, macOS, and Linux.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
