name: Build and Package App with PyInstaller

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller on Windows
        if: runner.os == 'Windows'
        run: pyinstaller App_PP.py --noconsole --onefile --distpath build/Kaalen-windows --name Kaalen-v.1.0 --icon icon.ico

      - name: Build with PyInstaller on macOS
        if: runner.os == 'macOS'
        run: pyinstaller App_PP.py --windowed --onefile --distpath build/Kaalen-macos --name Kaalen-v.1.0 --icon icon.ico

      - name: Build with PyInstaller on Linux
        if: runner.os == 'Linux'
        run: pyinstaller App_PP.py --onefile --distpath build/Kaalen-linux --name Kaalen-v.1.0

      - name: Prepare a zip file for the Windows release
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path "build/Kaalen-windows/*" -DestinationPath "build/Kaalen-windows.zip"

      - name: Prepare a zip file for the macOS release
        if: runner.os == 'macOS'
        run: |
          zip -r build/Kaalen-macos.zip build/Kaalen-macos/

      - name: Prepare a zip file for the Linux release
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          zip -r build/Kaalen-linux.zip build/Kaalen-linux/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/Kaalen-windows.zip
            build/Kaalen-macos.zip
            build/Kaalen-linux.zip
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}-${{ github.run_number }}
          body: |
            This is an automated release.
            
            This release includes a standalone executables for Windows, macOS, and Linux.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
