name: Build and Package App with cx-freeze

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cx-freeze and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx-freeze
          pip install -r requirements.txt

      - name: Create setup.py for cx-freeze
        run: |
          echo "from cx_Freeze import setup, Executable" > setup.py
          echo "import sys" >> setup.py
          echo "base = None" >> setup.py
          echo "if sys.platform == 'win32':" >> setup.py
          echo "    base = 'Win32GUI'" >> setup.py
          echo "setup(" >> setup.py
          echo "    name = 'Kaalen'," >> setup.py
          echo "    version = '1.0'," >> setup.py
          echo "    description = 'Kaalen 2D Signal Plotter App'," >> setup.py
          echo "    executables = [Executable('App_PP.py', base=base, icon='icon.ico', target_name='Kaalen.exe')]" >> setup.py
          echo ")" >> setup.py

      - name: Build with cx-freeze
        run: python setup.py build

      - name: Find and rename the executable
        id: find_exe
        run: |
          # The cx-freeze build directory name is dynamic. This command finds the first one.
          $buildDir = Get-ChildItem -Path .\build\ | Where-Object { $_.PSIsContainer } | Select-Object -First 1
          # Move the entire build directory to a predictable name for the artifact upload
          Move-Item -Path $buildDir.FullName -Destination .\build\Kaalen_App_dist

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kaalen-app-windows-dist
          path: build/Kaalen_App_dist
